db:
  host: '127.0.0.1'
  port: 3306,
  username: 'tobus_user'
  password: 'ju2JyI9Zjx'
  database: 'tobus_db'

jwt:
  secret:
    access: 'bKjFMNIA1e'
    refresh: 'DYpLWlvNdy'
  exp_time:
    access: '60s'
    refresh: '5m'
